[project]
name = "ai-search-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "aiohttp>=3.14.3",
    "curl-cffi>=0.16.0",
    "fastapi>=0.141.1",
    "instructor>=1.15.4",
    "litellm>=1.97.0",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=6.0.0",
    "sqlalchemy>=2.0.51",
    "tavily-python>=0.8.0",
    "torch>=2.13.0",
    "trafilatura>=2.2.0",
    "uvicorn>=0.52.1",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

